### PR TITLE
Add OAABData

### PR DESCRIPTION
**Pull request by IllusiveMan196**

### CODE REVIEW

**Comment by sibir-ine** [comment]
Are you just adding the URL? We don't really add entries with just URLs. Is there any other data you could add for the plugin? Also, that extra newline at the end isn't necessary.

**Comment by IllusiveMan196** [comment]
Adding this to reference for other mods (required masterfile, sort after...) newline is accidental. Next commits are a bit larger

**Comment by sibir-ine** [comment]
You can just link to it in relevant commit messages so other contributors know which mod you're referring to. I do that often.

**Comment by MacSplody** [comment]
They do have this in the MLOX list.

```
[ORDER]
OAAB_Data.esm
Wares-base.esm
Wares-*.esp
F&F_*.esp
```
You could place `OAAB_Data.esm` in the early loader group.

**Comment by IllusiveMan196** [comment]
So then it would be like this?

**Comment by MacSplody** [comment]
> So then it would be like this?

```yaml
  - name: 'OAAB_Data.esm'
    url: [ 'https://www.nexusmods.com/morrowind/mods/49042/' ]
    group: *earlyLoadersGroup
```

Yes, that would be fine.

**Review by MacSplody — APPROVED** [review]

**Comment by IllusiveMan196** [comment]
Add Tamriel_Data as separate PR?

**Comment by sibir-ine** [comment]
> 
> 
> Add Tamriel_Data as separate PR?

Yes.

**Comment by MacSplody** [comment]
@IllusiveMan196 Thanks.

**Pull request merged**
